### ISSUE TITLE
Will this project support to Swift 3.0?

### ISSUE THREAD

**Issue by ACChe** [mutualmobile/VIPER-SWIFT#16]
Will this project support to Swift 3.0?

**Comment by cnstoll** [comment]
I am sure we will update it eventually, but realistically probably not until Swift 3 stabilizes.

**Comment by speedoholic** [comment]
Any update on this support?

**Comment by JeffGilbert-MM** [comment]
We have an open PR to update the project to Swift 3.
https://github.com/mutualmobile/VIPER-SWIFT/pull/17

**Comment by muescha** [comment]
updated

issue can be closed

**Comment by ACChe** [comment]
I think It is time to update it to Swift 4.0.
